### ISSUE TITLE
Changes to files

### ISSUE THREAD

**Issue by amejiawes** [amejiawes/bootstrapclass#1]
**TODO**

* [x] Create Header on Bootstrap
* [ ] Create Main Banner
* [ ] Create Article Section 
* [ ] Create Footer

**Comment by amejiawes** [comment]
The code has been added back
